services:
  # Angular Frontend App

  frontend:
    extends:
      file: docker-compose.base.yml

      service: nx-app-base

    #command: npm run frontend:dev:docker
    #command: ['npm', 'run', 'fe-docker']
    command: nx serve metadata-analyzer-frontend --host 0.0.0.0

    ports:
      - 4200:4200

  # Nest Backend App
  backend:
    extends:
      file: docker-compose.base.yml

      service: nx-app-base

    #command: npm run backend:dev:docker
    #command: ['npm', 'run', 'be', '--host localhost']
    command: nx serve metadata-analyzer-backend --host localhost
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_DATABASE=${DATABASE_DATABASE}
    env_file:
      - .env.docker

    ports:
      - 3000:3000 # API Entry port

      # - 4311:4311 # Server Debugging port

  # Backend Database 
  backendDatabase:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5443:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  # Analyzer Database 
  analyzerDatabase:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5442:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres


volumes:
  mono-node-modules: null
