export const SIZE_ALERT = 'SIZE_ALERT';
export const CREATION_DATE_ALERT = 'CREATION_DATE_ALERT';
export const STORAGE_FILL_ALERT = 'STORAGE_FILL_ALERT';
export const MISSING_BACKUP_ALERT = 'MISSING_BACKUP_ALERT';
export const ADDITIONAL_BACKUP_ALERT = 'ADDITIONAL_BACKUP_ALERT';
