name: Analyzer Tests

on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'deliverables/**'
  pull_request:
    branches:
      - dev
    paths-ignore:
      - 'deliverables/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm ci
          cd ./apps/analyzer/metadata_analyzer
          python -m pip install --upgrade pip
          pip install pipx
          pipx install poetry
          poetry install

      # Step 4: Run tests
      - name: Run tests
        #working-directory: rootfolder/apps/analyzer
        run: npx nx run metadata-analyzer:test
